services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Tourze\BaiduTongjiApiBundle\Controller\:
    resource: '../../Controller/'
  Tourze\BaiduTongjiApiBundle\Repository\:
    resource: '../../Repository/'
    tags:
      - 'doctrine.repository_service'
  Tourze\BaiduTongjiApiBundle\Service\:
    resource: '../../Service/'
    public: true
  Tourze\BaiduTongjiApiBundle\Command\:
    resource: '../../Command/'

  # Service aliases
  tourze.baidu_tongji_api.client:
    alias: Tourze\BaiduTongjiApiBundle\Service\TongjiApiClient
    public: true
  tourze.baidu_tongji_api.site_service:
    alias: Tourze\BaiduTongjiApiBundle\Service\TongjiSiteService
    public: true
